name: Python Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-format-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Nếu bạn dùng Python 3.12 local

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Lint code
      run: |
        make lint
